-- =============================================================================
-- SED_ESAL - DDL Inicial
-- Esquema: SED_ESAL
-- Prefijo de tablas: ESAL_
-- Base de datos: Oracle
-- Fecha: 2026-05-15
-- =============================================================================

-- =============================================================================
-- SECUENCIAS
-- =============================================================================

CREATE SEQUENCE SED_ESAL.ESAL_ESAL_SEQ
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SED_ESAL.ESAL_PERSONERIA_SEQ
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SED_ESAL.ESAL_REFORMA_SEQ
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SED_ESAL.ESAL_NOMBRAMIENTO_SEQ
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SED_ESAL.ESAL_ORGANO_SEQ
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SED_ESAL.ESAL_ACTUACION_SEQ
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SED_ESAL.ESAL_DOCUMENTO_SEQ
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SED_ESAL.ESAL_CAMPO_SEQ
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SED_ESAL.ESAL_ADVERTENCIA_SEQ
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SED_ESAL.ESAL_AUDITORIA_SEQ
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- =============================================================================
-- TABLA: ESAL_ESAL
-- Entidad raiz del sistema
-- =============================================================================

CREATE TABLE SED_ESAL.ESAL_ESAL (
    ID                  NUMBER(19)      NOT NULL,
    NOMBRE              VARCHAR2(500)   NOT NULL,
    ID_SIPEJ            VARCHAR2(100),
    NIT                 VARCHAR2(50),
    DOMICILIO           VARCHAR2(500),
    CORREO_ELECTRONICO  VARCHAR2(255),
    TERMINO_DURACION    VARCHAR2(255),
    OBJETO_SOCIAL       CLOB,
    ESTADO              VARCHAR2(30)    NOT NULL,
    ESTADO_COMPLETITUD  VARCHAR2(40)    NOT NULL,
    CREATED_AT          TIMESTAMP,
    CREATED_BY          VARCHAR2(255),
    UPDATED_AT          TIMESTAMP,
    UPDATED_BY          VARCHAR2(255),
    CONSTRAINT PK_ESAL_ESAL PRIMARY KEY (ID),
    CONSTRAINT UQ_ESAL_ID_SIPEJ UNIQUE (ID_SIPEJ),
    CONSTRAINT CK_ESAL_ESTADO CHECK (ESTADO IN ('ACTIVO','SUSPENDIDO','EN_LIQUIDACION','CANCELADO')),
    CONSTRAINT CK_ESAL_COMPLETITUD CHECK (ESTADO_COMPLETITUD IN ('LISTO_PARA_CERTIFICAR','INCOMPLETO_NO_BLOQUEANTE','INCOMPLETO_BLOQUEANTE'))
);

CREATE INDEX IDX_ESAL_ID_SIPEJ ON SED_ESAL.ESAL_ESAL (ID_SIPEJ);
CREATE INDEX IDX_ESAL_ESTADO   ON SED_ESAL.ESAL_ESAL (ESTADO);

-- =============================================================================
-- TABLA: ESAL_PERSONERIA_JURIDICA
-- =============================================================================

CREATE TABLE SED_ESAL.ESAL_PERSONERIA_JURIDICA (
    ID                                      NUMBER(19)  NOT NULL,
    ESAL_ID                                 NUMBER(19)  NOT NULL,
    RECONOCIMIENTO_PERSONERIA_JURIDICA      VARCHAR2(500),
    FECHA_RECONOCIMIENTO_PERSONERIA_JURIDICA DATE,
    ENTIDAD_QUE_EXPIDE                      VARCHAR2(500),
    INSCRIPCION                             VARCHAR2(500),
    FECHA_INSCRIPCION                       DATE,
    ENTIDAD_QUE_INSCRIBIO                   VARCHAR2(500),
    CONSTRAINT PK_ESAL_PERSONERIA PRIMARY KEY (ID),
    CONSTRAINT FK_PERSONERIA_ESAL FOREIGN KEY (ESAL_ID) REFERENCES SED_ESAL.ESAL_ESAL (ID)
);

CREATE INDEX IDX_PERSONERIA_ESAL_ID ON SED_ESAL.ESAL_PERSONERIA_JURIDICA (ESAL_ID);

-- =============================================================================
-- TABLA: ESAL_REFORMA_ESTATUTARIA
-- =============================================================================

CREATE TABLE SED_ESAL.ESAL_REFORMA_ESTATUTARIA (
    ID              NUMBER(19)      NOT NULL,
    ESAL_ID         NUMBER(19)      NOT NULL,
    ORDEN           NUMBER(10),
    TIPO_ACTO       VARCHAR2(255),
    NUMERO_ACTO     VARCHAR2(255),
    FECHA_ACTO      DATE,
    ENTIDAD_QUE_EXPIDE VARCHAR2(500),
    DESCRIPCION     VARCHAR2(1000),
    CONSTRAINT PK_ESAL_REFORMA PRIMARY KEY (ID),
    CONSTRAINT FK_REFORMA_ESAL FOREIGN KEY (ESAL_ID) REFERENCES SED_ESAL.ESAL_ESAL (ID)
);

CREATE INDEX IDX_REFORMA_ESAL_ID ON SED_ESAL.ESAL_REFORMA_ESTATUTARIA (ESAL_ID);

-- =============================================================================
-- TABLA: ESAL_NOMBRAMIENTO
-- =============================================================================

CREATE TABLE SED_ESAL.ESAL_NOMBRAMIENTO (
    ID                      NUMBER(19)      NOT NULL,
    ESAL_ID                 NUMBER(19)      NOT NULL,
    TIPO_NOMBRAMIENTO       VARCHAR2(50)    NOT NULL,
    NOMBRE                  VARCHAR2(500),
    TIPO_DOCUMENTO          VARCHAR2(50),
    NUMERO_DOCUMENTO        VARCHAR2(100),
    CARGO                   VARCHAR2(255),
    ACTA_APRUEBA            VARCHAR2(255),
    FECHA_ACTA              DATE,
    TARJETA_PROFESIONAL     VARCHAR2(255),
    FACULTADES_LIMITACIONES VARCHAR2(1000),
    VIGENTE                 NUMBER(1)       DEFAULT 1,
    CONSTRAINT PK_ESAL_NOMBRAMIENTO PRIMARY KEY (ID),
    CONSTRAINT FK_NOMBRAMIENTO_ESAL FOREIGN KEY (ESAL_ID) REFERENCES SED_ESAL.ESAL_ESAL (ID),
    CONSTRAINT CK_NOMBRAMIENTO_TIPO CHECK (TIPO_NOMBRAMIENTO IN (
        'REPRESENTANTE_LEGAL','REPRESENTANTE_LEGAL_SUPLENTE',
        'REVISOR_FISCAL_PRINCIPAL','REVISOR_FISCAL_SUPLENTE',
        'TESORERO','DIGNATARIO'))
);

CREATE INDEX IDX_NOMBRAMIENTO_ESAL_ID ON SED_ESAL.ESAL_NOMBRAMIENTO (ESAL_ID);

-- =============================================================================
-- TABLA: ESAL_ORGANO_ADMINISTRACION
-- =============================================================================

CREATE TABLE SED_ESAL.ESAL_ORGANO_ADMINISTRACION (
    ID                      NUMBER(19)      NOT NULL,
    ESAL_ID                 NUMBER(19)      NOT NULL,
    ORGANO                  VARCHAR2(255),
    MIEMBRO                 VARCHAR2(500),
    CARGO                   VARCHAR2(255),
    TIPO_DOCUMENTO          VARCHAR2(50),
    NUMERO_DOCUMENTO        VARCHAR2(100),
    ACTA_APRUEBA            VARCHAR2(255),
    FECHA_ACTA              DATE,
    ACTA_ACLARATORIA        VARCHAR2(255),
    FECHA_ACTA_ACLARATORIA  DATE,
    FACULTADES_LIMITACIONES VARCHAR2(1000),
    CONSTRAINT PK_ESAL_ORGANO PRIMARY KEY (ID),
    CONSTRAINT FK_ORGANO_ESAL FOREIGN KEY (ESAL_ID) REFERENCES SED_ESAL.ESAL_ESAL (ID)
);

CREATE INDEX IDX_ORGANO_ESAL_ID ON SED_ESAL.ESAL_ORGANO_ADMINISTRACION (ESAL_ID);

-- =============================================================================
-- TABLA: ESAL_ACTUACION_ADMINISTRATIVA
-- =============================================================================

CREATE TABLE SED_ESAL.ESAL_ACTUACION_ADMINISTRATIVA (
    ID                  NUMBER(19)      NOT NULL,
    ESAL_ID             NUMBER(19)      NOT NULL,
    TIPO_ACTUACION      VARCHAR2(30)    NOT NULL,
    ACTA                VARCHAR2(255),
    FECHA_ACTA          DATE,
    RESOLUCION          VARCHAR2(255),
    FECHA_RESOLUCION    DATE,
    MOTIVO              VARCHAR2(1000),
    TIEMPO_SUSPENSION   VARCHAR2(255),
    FECHA_INICIO        DATE,
    FECHA_FIN           DATE,
    CONSTRAINT PK_ESAL_ACTUACION PRIMARY KEY (ID),
    CONSTRAINT FK_ACTUACION_ESAL FOREIGN KEY (ESAL_ID) REFERENCES SED_ESAL.ESAL_ESAL (ID),
    CONSTRAINT CK_ACTUACION_TIPO CHECK (TIPO_ACTUACION IN ('SUSPENSION','LIQUIDACION','CANCELACION'))
);

CREATE INDEX IDX_ACTUACION_ESAL_ID ON SED_ESAL.ESAL_ACTUACION_ADMINISTRATIVA (ESAL_ID);

-- =============================================================================
-- TABLA: ESAL_DOCUMENTO_SOPORTE
-- =============================================================================

CREATE TABLE SED_ESAL.ESAL_DOCUMENTO_SOPORTE (
    ID                  NUMBER(19)      NOT NULL,
    ESAL_ID             NUMBER(19)      NOT NULL,
    TIPO_PROCESO        VARCHAR2(255),
    TIPO_DOCUMENTO      VARCHAR2(255),
    NOMBRE_ARCHIVO      VARCHAR2(500)   NOT NULL,
    CONTENT_TYPE        VARCHAR2(100)   NOT NULL,
    TAMANO_BYTES        NUMBER(19),
    RUTA_ALMACENAMIENTO VARCHAR2(1000),
    ESTADO_VALIDACION   VARCHAR2(20)    DEFAULT 'PENDIENTE',
    CREATED_AT          TIMESTAMP,
    CREATED_BY          VARCHAR2(255),
    CONSTRAINT PK_ESAL_DOCUMENTO PRIMARY KEY (ID),
    CONSTRAINT FK_DOCUMENTO_ESAL FOREIGN KEY (ESAL_ID) REFERENCES SED_ESAL.ESAL_ESAL (ID),
    CONSTRAINT CK_DOCUMENTO_ESTADO CHECK (ESTADO_VALIDACION IN ('PENDIENTE','VALIDO','RECHAZADO'))
);

CREATE INDEX IDX_DOCUMENTO_ESAL_ID ON SED_ESAL.ESAL_DOCUMENTO_SOPORTE (ESAL_ID);

-- =============================================================================
-- TABLA: ESAL_CAMPO_OBLIGATORIEDAD
-- =============================================================================

CREATE TABLE SED_ESAL.ESAL_CAMPO_OBLIGATORIEDAD (
    ID              NUMBER(19)      NOT NULL,
    NOMBRE_CAMPO    VARCHAR2(255)   NOT NULL,
    SECCION         VARCHAR2(255),
    CONTEXTO        VARCHAR2(500),
    OBLIGATORIO     NUMBER(1)       NOT NULL,
    NOTA            VARCHAR2(1000),
    ORDEN           NUMBER(10),
    CONSTRAINT PK_ESAL_CAMPO PRIMARY KEY (ID)
);

CREATE INDEX IDX_CAMPO_OBLIGATORIO ON SED_ESAL.ESAL_CAMPO_OBLIGATORIEDAD (OBLIGATORIO);
CREATE INDEX IDX_CAMPO_SECCION     ON SED_ESAL.ESAL_CAMPO_OBLIGATORIEDAD (SECCION);

-- =============================================================================
-- TABLA: ESAL_ADVERTENCIA_COMPLETITUD
-- =============================================================================

CREATE TABLE SED_ESAL.ESAL_ADVERTENCIA_COMPLETITUD (
    ID          NUMBER(19)      NOT NULL,
    ESAL_ID     NUMBER(19)      NOT NULL,
    SECCION     VARCHAR2(255),
    CAMPO       VARCHAR2(255),
    TIPO        VARCHAR2(50)    NOT NULL,
    BLOQUEANTE  NUMBER(1)       NOT NULL,
    MENSAJE     VARCHAR2(1000),
    CREATED_AT  TIMESTAMP,
    CONSTRAINT PK_ESAL_ADVERTENCIA PRIMARY KEY (ID),
    CONSTRAINT FK_ADVERTENCIA_ESAL FOREIGN KEY (ESAL_ID) REFERENCES SED_ESAL.ESAL_ESAL (ID),
    CONSTRAINT CK_ADVERTENCIA_TIPO CHECK (TIPO IN (
        'CAMPO_OBLIGATORIO_FALTANTE','DOCUMENTO_REQUERIDO_FALTANTE',
        'DATO_INCONSISTENTE','ADVERTENCIA_HISTORICA'))
);

CREATE INDEX IDX_ADVERTENCIA_ESAL_ID    ON SED_ESAL.ESAL_ADVERTENCIA_COMPLETITUD (ESAL_ID);
CREATE INDEX IDX_ADVERTENCIA_BLOQUEANTE ON SED_ESAL.ESAL_ADVERTENCIA_COMPLETITUD (BLOQUEANTE);

-- =============================================================================
-- TABLA: ESAL_AUDITORIA
-- =============================================================================

CREATE TABLE SED_ESAL.ESAL_AUDITORIA (
    ID          NUMBER(19)      NOT NULL,
    USUARIO     VARCHAR2(255)   NOT NULL,
    ROL         VARCHAR2(100),
    ACCION      VARCHAR2(255)   NOT NULL,
    ENTIDAD     VARCHAR2(255),
    ENTIDAD_ID  NUMBER(19),
    ID_SIPEJ    VARCHAR2(100),
    RESULTADO   VARCHAR2(100),
    DETALLE     VARCHAR2(2000),
    CREATED_AT  TIMESTAMP       NOT NULL,
    CONSTRAINT PK_ESAL_AUDITORIA PRIMARY KEY (ID)
);

CREATE INDEX IDX_AUDITORIA_USUARIO    ON SED_ESAL.ESAL_AUDITORIA (USUARIO);
CREATE INDEX IDX_AUDITORIA_ENTIDAD    ON SED_ESAL.ESAL_AUDITORIA (ENTIDAD, ENTIDAD_ID);
CREATE INDEX IDX_AUDITORIA_CREATED_AT ON SED_ESAL.ESAL_AUDITORIA (CREATED_AT);
